### ISSUE TITLE
As a developer, I want to refactor the file structure of the project, so that data percistence resides in a library project 2.2b

### ISSUE THREAD

**Issue by palleBrandt** [ITU-BDSA23-GROUP12/Chirp#10]
**User story**
As a developer, I want to prep the file structure of the project, so that it is ready for a refactoring of data persistence.

**Description of the solution you'd like**
2.2b
The reading- and storing of data from a csv-file should be refactored so that it resides in a library project, on which Chirp.CLI should depend. 

**Definition of Done**
- [x] Create a .NET classlib project called SimpleDB.
- [x] Insert into the SimpleDB, the IDatabaseRepository<T> interface from session_02
- [x] Inside SimpleDB, create a class CSVDatabase<T>
- [x] Implement CSVDatabase<T> that follows requirements from 2.2b

**Comment by palleBrandt** [comment]
**Status**

CSVDatabase handling of read works. 

Still need:
- to implement store functionality.
- to fix that it shall not be possible to create further sub-classes of class CSVDatabase<T>

**Comment by allanzigge** [comment]
Branch: Issue10
