### ISSUE TITLE
As a developer i would like to adapt the test suite, so that End 2 End test works.

### ISSUE THREAD

**Issue by palleBrandt** [ITU-BDSA23-GROUP12/Chirp#118]
**User Story**
As a developer i would like to adapt the test suite, so that End 2 End test works.

**Description of the solution you'd like**
After the implementation of web api, the end to end test no longer works. The test suite has to be adapted so that it works with the new implementation of web api.

**Definition of Done**
- [x] The end to end test should compile and be pass after the adaption of the test suite.

**Comment by Maquidos** [comment]
First review

Looks good, but a test of "limit -1" and just "read" or "limit x"
where x>totalt cheeps, to test if there is some exceptions thrown.
The Test_That_A_Cheep_Is_Stored_As_Expected should maybe not be
dependened on the read limit 1
