### ISSUE TITLE
As a developer i would like to edit the yaml files so they follow project guidelines

### ISSUE THREAD

**Issue by palleBrandt** [ITU-BDSA23-GROUP12/Chirp#132]
**User Story**
As a developer i would like to edit the yaml files so they follow project guidelines

**Description of the solution you'd like**
After changing our git strategy, as a result of the 1. project review, the workflows of this project should be edited so they fit the outlined guides from session 03.

**Definition of Done**
- [x] Remove mergeToMainWorkFlow
- [x] Clean up the release workflow, so it no longer uses matrix.
- [x] The build and test workflow should still work as expected.

**Comment by Maquidos** [comment]
We still use matix, because it is best
