### ISSUE TITLE
As a developer, I would like that user interface code resides in a separate class to depend on acceptance (2.2c)

### ISSUE THREAD

**Issue by allanzigge** [ITU-BDSA23-GROUP12/Chirp#19]
**User Story**
As a developer, I would like that user interface code resides in a separate class to depend on acceptance (2.2c)

**Description of the solutions you'd like**
See picture in 2.2c
I would like to have the function  ` void PrintCheeps(IEnumerable<Cheep> cheeps)`

**Definition of Done**
Have a class containing a function to print cheeps.

**Comment by palleBrandt** [comment]
Review approved, would like another teammember to join for merging
