### ISSUE TITLE
As a developer I want to implement a way to reduce code redundancy in posting of cheeps

### ISSUE THREAD

**Issue by palleBrandt** [ITU-BDSA23-GROUP12/Chirp#266]
**User Story**
As a developer I want to implement a way to reduce code redundancy in posting of cheeps

**Description of the solution you'd like**
Right now we have the same onpost method on both the usertimeline and the public timeline. Code redundancy. We would like to instead, find a way to get rid of this. Maybe use View Components. Read in the book

**Definition of Done**
- [ ] Code redundancy is gone
- [ ] Also use same way of removing code redundancy for the pagination component.

**Comment by allanzigge** [comment]
@kartoffelmozart  did this
