### ISSUE TITLE
12/ 2.A.(3))  As a Developer, I want a method that sets the respectively cheeps isDeleted: true, to make way for functionality to not show these entities in our application

### ISSUE THREAD

**Issue by Maquidos** [ITU-BDSA23-GROUP12/Chirp#300]
**User Story**
As a Developer, I want a method that sets the respectively cheeps isDeleted: true, to make way for functionality to not show these entities in our application

**Description of the solution you'd like**
The OnPost methode "DeleteUser"  should trigger a methode in our repository which findes all cheeps related to the user an set there attribute "isDeleted" to true.

**Definition of Done**
- [ ] Use GetCheep from cheeprepository to update their attribute "isDeleted": true

**Comment by palleBrandt** [comment]
It has been implemented so that author has the IsDeleted boolean instead. Cheeps contains their author, and therefor you can call Cheep.Author.IsDeleted
