### ISSUE TITLE
As a developer i would like the file structure of this project to follow recommendations

### ISSUE THREAD

**Issue by palleBrandt** [ITU-BDSA23-GROUP12/Chirp#33]
**User Story**
As a developer i would like the file structure of this project to follow recommendations

**Description of the solution you'd like**
Refactor the file structure of our project, so that it follows the recommended structure, outlined in lecture 03

**Definition of Done**
- [ ]  The file structure of our project should follow the recommendations from lecture 03 under a src folder

**Comment by Maquidos** [comment]
We need to move our CSV file to a new folder called Data

And then all references to the CSV file have to be redirected, in all other files
