### ISSUE TITLE
As a developer i want to make the forget me button red, so it follows what is outlined at lectures.

### ISSUE THREAD

**Issue by palleBrandt** [ITU-BDSA23-GROUP12/Chirp#339]
**User Story**
As a developer i want to make the forget me button red, so it follows what is outlined at lectures.

**Description of the solution you'd like**

**Definition of Done**
- [x] Forget me button should be red

**Comment by allanzigge** [comment]
add pop up when click forget me 

"Are you sure you want to delete"
