### ISSUE TITLE
As a developer i want to add comment and references to my code, to make it better to understand

### ISSUE THREAD

**Issue by palleBrandt** [ITU-BDSA23-GROUP12/Chirp#341]
**User Story**
As a developer i want to add comment and references to my code, to make it better to understand

**Description of the solution you'd like**
Read through and find places that needs comments, and also places that might need references.

**Definition of Done**
- [ ] Add comments
- [ ] Add references

**Comment by allanzigge** [comment]
Should we clean up, i.e. delete unnecessary "using's" ?
