### ISSUE TITLE
Process - How to make Chirp! work locally

### ISSUE THREAD

**Issue by Maquidos** [ITU-BDSA23-GROUP12/Chirp#367]
_There has to be some documentation on how to come from cloning your project to a running system. That is, Rasmus or Helge have to know precisely what to do in which order. Likely, it is best to describe how we clone your project, which commands we have to execute, and what we are supposed to see then._

**Comment by palleBrandt** [comment]
In the guide to how to make Chirp run locally I had to write instructions to creating the secret we use for deletion. Now the only problem is due to our repository rules, i am not allowed to push.
