### ISSUE TITLE
As developer, we want to implement CsvHelper to make it simple to handle input from the user

### ISSUE THREAD

**Issue by RazzerTazzer** [ITU-BDSA23-GROUP12/Chirp#7]
**User Story**
As developer, we want to implement CsvHelper to make it simple to handle input from the user

**Describe the Solution**
Show helper window of commands, when the input is not regonized, set up commands for "read" and "write" such that it  our program can execute storing and writing to the csv file 

**Definitions of Done**
- [x] Get csvHelper running in the project file 
- [x] Implement it such that it knows "read" and "write"

**Comment by RazzerTazzer** [comment]
- figure out how to import Csvhelper to the project
- figure out how we want to implement it

**Comment by palleBrandt** [comment]
This issue is based upon session_02/README_PROJECT.md 2.a
