### ISSUE TITLE
As a developer, we want to store Cheeps as records, such that it is easier to access and store data

### ISSUE THREAD

**Issue by RazzerTazzer** [ITU-BDSA23-GROUP12/Chirp#8]
**User Story**
As a developer, we want to store Cheeps as records, such that it is easier to access and store data

**Describe the Solution you would like**
- [x] Find out how to use records
- [x] Find out how we want to implement it 
- [x] Be able to store Author, timestamp and cheep as variables

**Definition of Done**
When it is implemented and it is possible to retrieve and store cheeps

**Comment by palleBrandt** [comment]
This issue is based upon session_02/README_PROJECT.md 2.a
