### ISSUE TITLE
As a developer, I would like to auto build, test & publish releases to save time 3.1.a

### ISSUE THREAD

**Issue by allanzigge** [ITU-BDSA23-GROUP12/Chirp#80]
**User Story**
This issue is based on task [3.1.a](https://github.com/itu-bdsa/lecture_notes/blob/main/sessions/session_03/README_PROJECT.md)
To save time building, testing and merging our code we want to automate these things to satisfy our expectations in different situations.

**Definition of Done**

- [x] Add workflow to automatically merge the development branch to main, if the development branch works. 
- [ ] Add workflow to automatically create release (maybe one for each OS - win, mac-os, linux) as zip file

**Comment by palleBrandt** [comment]
Auto publish with releases work, but I am having problems with the single file applications generated not being able to find the correct path for our file. I think its something with how we assign our path to the csv file.
