### ISSUE TITLE
Consideration on Ethics Telemetry optout (session_03 - README_PROJECT.md - section 3 Ethics)

### ISSUE THREAD

**Issue by Maquidos** [ITU-BDSA23-GROUP12/Chirp#93]
The [.NET SDK](https://learn.microsoft.com/en-us/dotnet/core/tools/) includes a telemetry feature that collects usage data and sends it to Microsoft when you use [.NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tools/) commands. The usage data includes exception information when the .NET CLI crashes. The .NET CLI comes with the .NET SDK and is the set of verbs that enable you to build, test, and publish your .NET apps. Telemetry data helps the .NET team understand how the tools are used so they can be improved. Information on failures helps the team resolve problems and fix bugs.

from : https://learn.microsoft.com/en-us/dotnet/core/tools/telemetry

We can choose to optout by using:

The .NET SDK telemetry feature is enabled by default for Microsoft distributions of the SDK. To opt out of the telemetry feature, set the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 or true.

**Should we optout??**

**Comment by RazzerTazzer** [comment]
I think we are done with using CLI in project. That is my understanding at least :j

**Comment by allanzigge** [comment]
We have decided that the information we are storing (and going to store) is not sensitive. Therefore we are not going to restrict data collection.
